/*
 * orion_lib.h
 *
 *  Created on: Aug 5, 2024
 *  Author: jeanfrancois
 *  v1.1.100 1-Sep-2024
 */

#ifndef USER_OL_LIB_H_
#define USER_OL_LIB_H_

#include "debug.h"

// Supported boards

// User defined board
// EVK_CH32V003_GENERIC, CE_NUNKI_MICRO_CH32V003F

// User Configuration

#define CE_NUNKI_MICRO_CH32V003F

// Boards Layout

/*
 * Generic EVK board (manufactured by WCH, ...)
 * WCH CH32V003F 4P6-R0-1v1 Pin Layout
 *
 * Header GPIO     MCU Pin
 *
 *      02 01  <-> PD4 PD5
 *      04 03  <-> PD6 PD7
 *      06 05  <-> PD0 PC0
 *      08 07  <-> PD3 PD1
 *      10 09  <-> PD2 PC7
 *      12 11  <-> PC6 PC5
 *      14 13  <-> PC4 PC3
 *      16 15  <-> PC2 PC1
 */

// #define CE_NUNKI_MICRO_CH32V003F

/*
 * NUNKI-MICRO-CH32V003 (manufactured by Chrysalide Engineering)
 *
 * Header GPIO     MCU Pin
 *
 *      01 02 <-> PD5 PD7
 *      03 04 <-> PC0 PD1
 *      05 06 <-> PC7 PD5
 *      07 08 <-> PC3 PD1
 *      09 10 <-> PC2 PD4
 *      11 12 <-> PC6 PD2
 *      13 14 <-> PD3 PD0
 *      15 16 <-> PD6 PD4
 */

extern GPIO_TypeDef * ol_port_map[];
extern uint16_t ol_pin_map[];

// User Map

#define OL_GPIO_01 1
#define OL_GPIO_02 2
#define OL_GPIO_03 3
#define OL_GPIO_04 4
#define OL_GPIO_05 5
#define OL_GPIO_06 6
#define OL_GPIO_07 7
#define OL_GPIO_08 8
#define OL_GPIO_09 9
#define OL_GPIO_10 10
#define OL_GPIO_11 11
#define OL_GPIO_12 12
#define OL_GPIO_13 13
#define OL_GPIO_14 14
#define OL_GPIO_15 15
#define OL_GPIO_16 16

// Implementation details

#ifdef EVK_CH32V003_GENERIC
#define OL_GPIO_01_PORT GPIOD
#define OL_GPIO_01_PIN  GPIO_Pin_5
#define OL_GPIO_02_PORT GPIOD
#define OL_GPIO_02_PIN  GPIO_Pin_4
#define OL_GPIO_03_PORT GPIOD
#define OL_GPIO_03_PIN  GPIO_Pin_7
#define OL_GPIO_04_PORT GPIOD
#define OL_GPIO_04_PIN  GPIO_Pin_6
#define OL_GPIO_05_PORT GPIOC
#define OL_GPIO_05_PIN  GPIO_Pin_0
#define OL_GPIO_06_PORT GPIOD
#define OL_GPIO_06_PIN  GPIO_Pin_0
#define OL_GPIO_07_PORT GPIOD
#define OL_GPIO_07_PIN  GPIO_Pin_1
#define OL_GPIO_08_PORT GPIOD
#define OL_GPIO_08_PIN  GPIO_Pin_3
#define OL_GPIO_09_PORT GPIOC
#define OL_GPIO_09_PIN  GPIO_Pin_7
#define OL_GPIO_10_PORT GPIOD
#define OL_GPIO_10_PIN  GPIO_Pin_2
#define OL_GPIO_11_PORT GPIOC
#define OL_GPIO_11_PIN  GPIO_Pin_5
#define OL_GPIO_12_PORT GPIOC
#define OL_GPIO_12_PIN  GPIO_Pin_6
#define OL_GPIO_13_PORT GPIOC
#define OL_GPIO_13_PIN  GPIO_Pin_3
#define OL_GPIO_14_PORT GPIOC
#define OL_GPIO_14_PIN  GPIO_Pin_4
#define OL_GPIO_15_PORT GPIOC
#define OL_GPIO_15_PIN  GPIO_Pin_1
#define OL_GPIO_16_PORT GPIOC
#define OL_GPIO_16_PIN  GPIO_Pin_2
#endif

#ifdef CE_NUNKI_MICRO_CH32V003F
#define OL_GPIO_01_PORT GPIOD
#define OL_GPIO_01_PIN  GPIO_Pin_5
#define OL_GPIO_02_PORT GPIOD
#define OL_GPIO_02_PIN  GPIO_Pin_7
#define OL_GPIO_03_PORT GPIOC
#define OL_GPIO_03_PIN  GPIO_Pin_0
#define OL_GPIO_04_PORT GPIOC
#define OL_GPIO_04_PIN  GPIO_Pin_1
#define OL_GPIO_05_PORT GPIOC
#define OL_GPIO_05_PIN  GPIO_Pin_7
#define OL_GPIO_06_PORT GPIOC
#define OL_GPIO_06_PIN  GPIO_Pin_5
#define OL_GPIO_07_PORT GPIOC
#define OL_GPIO_07_PIN  GPIO_Pin_3
#define OL_GPIO_08_PORT GPIOC
#define OL_GPIO_08_PIN  GPIO_Pin_1
#define OL_GPIO_09_PORT GPIOC
#define OL_GPIO_09_PIN  GPIO_Pin_2
#define OL_GPIO_10_PORT GPIOC
#define OL_GPIO_10_PIN  GPIO_Pin_4
#define OL_GPIO_11_PORT GPIOC
#define OL_GPIO_11_PIN  GPIO_Pin_6
#define OL_GPIO_12_PORT GPIOD
#define OL_GPIO_12_PIN  GPIO_Pin_2
#define OL_GPIO_13_PORT GPIOD
#define OL_GPIO_13_PIN  GPIO_Pin_3
#define OL_GPIO_14_PORT GPIOD
#define OL_GPIO_14_PIN  GPIO_Pin_0
#define OL_GPIO_15_PORT GPIOD
#define OL_GPIO_15_PIN  GPIO_Pin_6
#define OL_GPIO_16_PORT GPIOD
#define OL_GPIO_16_PIN  GPIO_Pin_4
#endif

// Optimized (1 call function)
#define GPIO_01_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_01_PORT, OL_GPIO_01_PIN, vin)
#define GPIO_02_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_02_PORT, OL_GPIO_02_PIN, vin)
#define GPIO_03_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_03_PORT, OL_GPIO_03_PIN, vin)
#define GPIO_04_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_04_PORT, OL_GPIO_04_PIN, vin)
#define GPIO_05_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_05_PORT, OL_GPIO_05_PIN, vin)
#define GPIO_06_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_06_PORT, OL_GPIO_06_PIN, vin)
#define GPIO_07_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_07_PORT, OL_GPIO_07_PIN, vin)
#define GPIO_08_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_08_PORT, OL_GPIO_08_PIN, vin)
#define GPIO_09_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_09_PORT, OL_GPIO_09_PIN, vin)
#define GPIO_10_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_10_PORT, OL_GPIO_10_PIN, vin)
#define GPIO_11_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_11_PORT, OL_GPIO_11_PIN, vin)
#define GPIO_12_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_12_PORT, OL_GPIO_12_PIN, vin)
#define GPIO_13_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_13_PORT, OL_GPIO_13_PIN, vin)
#define GPIO_14_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_14_PORT, OL_GPIO_14_PIN, vin)
#define GPIO_15_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_15_PORT, OL_GPIO_15_PIN, vin)
#define GPIO_16_DIGITAL_WRITE(vin) GPIO_WriteBit(OL_GPIO_16_PORT, OL_GPIO_16_PIN, vin)

#define GPIO_01_DIGITAL_SET() 	(OL_GPIO_01_PORT->BSHR = OL_GPIO_01_PIN)
#define GPIO_01_DIGITAL_CLEAR() (OL_GPIO_01_PORT->BCR = OL_GPIO_01_PIN)
#define GPIO_02_DIGITAL_SET() 	(OL_GPIO_02_PORT->BSHR = OL_GPIO_02_PIN)
#define GPIO_02_DIGITAL_CLEAR() (OL_GPIO_02_PORT->BCR = OL_GPIO_02_PIN)
#define GPIO_03_DIGITAL_SET() 	(OL_GPIO_03_PORT->BSHR = OL_GPIO_03_PIN)
#define GPIO_03_DIGITAL_CLEAR() (OL_GPIO_03_PORT->BCR = OL_GPIO_03_PIN)
#define GPIO_04_DIGITAL_SET() 	(OL_GPIO_04_PORT->BSHR = OL_GPIO_04_PIN)
#define GPIO_04_DIGITAL_CLEAR() (OL_GPIO_04_PORT->BCR = OL_GPIO_04_PIN)
#define GPIO_05_DIGITAL_SET() 	(OL_GPIO_05_PORT->BSHR = OL_GPIO_05_PIN)
#define GPIO_05_DIGITAL_CLEAR() (OL_GPIO_05_PORT->BCR = OL_GPIO_05_PIN)
#define GPIO_06_DIGITAL_SET() 	(OL_GPIO_06_PORT->BSHR = OL_GPIO_06_PIN)
#define GPIO_06_DIGITAL_CLEAR() (OL_GPIO_06_PORT->BCR = OL_GPIO_06_PIN)
#define GPIO_07_DIGITAL_SET() 	(OL_GPIO_07_PORT->BSHR = OL_GPIO_07_PIN)
#define GPIO_07_DIGITAL_CLEAR() (OL_GPIO_07_PORT->BCR = OL_GPIO_07_PIN)
#define GPIO_08_DIGITAL_SET() 	(OL_GPIO_08_PORT->BSHR = OL_GPIO_08_PIN)
#define GPIO_08_DIGITAL_CLEAR() (OL_GPIO_08_PORT->BCR = OL_GPIO_08_PIN)
#define GPIO_09_DIGITAL_SET() 	(OL_GPIO_09_PORT->BSHR = OL_GPIO_09_PIN)
#define GPIO_09_DIGITAL_CLEAR() (OL_GPIO_09_PORT->BCR = OL_GPIO_09_PIN)
#define GPIO_10_DIGITAL_SET() 	(OL_GPIO_10_PORT->BSHR = OL_GPIO_10_PIN)
#define GPIO_10_DIGITAL_CLEAR() (OL_GPIO_10_PORT->BCR = OL_GPIO_10_PIN)
#define GPIO_11_DIGITAL_SET() 	(OL_GPIO_11_PORT->BSHR = OL_GPIO_11_PIN)
#define GPIO_11_DIGITAL_CLEAR() (OL_GPIO_11_PORT->BCR = OL_GPIO_11_PIN)
#define GPIO_12_DIGITAL_SET() 	(OL_GPIO_12_PORT->BSHR = OL_GPIO_12_PIN)
#define GPIO_12_DIGITAL_CLEAR() (OL_GPIO_12_PORT->BCR = OL_GPIO_12_PIN)
#define GPIO_13_DIGITAL_SET() 	(OL_GPIO_13_PORT->BSHR = OL_GPIO_13_PIN)
#define GPIO_13_DIGITAL_CLEAR() (OL_GPIO_13_PORT->BCR = OL_GPIO_13_PIN)
#define GPIO_14_DIGITAL_SET() 	(OL_GPIO_14_PORT->BSHR = OL_GPIO_14_PIN)
#define GPIO_14_DIGITAL_CLEAR() (OL_GPIO_14_PORT->BCR = OL_GPIO_14_PIN)
#define GPIO_15_DIGITAL_SET() 	(OL_GPIO_15_PORT->BSHR = OL_GPIO_15_PIN)
#define GPIO_15_DIGITAL_CLEAR() (OL_GPIO_15_PORT->BCR = OL_GPIO_15_PIN)
#define GPIO_16_DIGITAL_SET() 	(OL_GPIO_16_PORT->BSHR = OL_GPIO_16_PIN)
#define GPIO_16_DIGITAL_CLEAR() (OL_GPIO_16_PORT->BCR = OL_GPIO_16_PIN)

#define GPIO_01_DIGITAL_READ() (OL_GPIO_01_PORT->INDR & OL_GPIO_01_PIN)
#define GPIO_02_DIGITAL_READ() (OL_GPIO_02_PORT->INDR & OL_GPIO_02_PIN)
#define GPIO_03_DIGITAL_READ() (OL_GPIO_03_PORT->INDR & OL_GPIO_03_PIN)
#define GPIO_04_DIGITAL_READ() (OL_GPIO_04_PORT->INDR & OL_GPIO_04_PIN)
#define GPIO_05_DIGITAL_READ() (OL_GPIO_05_PORT->INDR & OL_GPIO_05_PIN)
#define GPIO_06_DIGITAL_READ() (OL_GPIO_06_PORT->INDR & OL_GPIO_06_PIN)
#define GPIO_07_DIGITAL_READ() (OL_GPIO_07_PORT->INDR & OL_GPIO_07_PIN)
#define GPIO_08_DIGITAL_READ() (OL_GPIO_08_PORT->INDR & OL_GPIO_08_PIN)
#define GPIO_09_DIGITAL_READ() (OL_GPIO_09_PORT->INDR & OL_GPIO_09_PIN)
#define GPIO_10_DIGITAL_READ() (OL_GPIO_10_PORT->INDR & OL_GPIO_10_PIN)
#define GPIO_11_DIGITAL_READ() (OL_GPIO_11_PORT->INDR & OL_GPIO_11_PIN)
#define GPIO_12_DIGITAL_READ() (OL_GPIO_12_PORT->INDR & OL_GPIO_12_PIN)
#define GPIO_13_DIGITAL_READ() (OL_GPIO_13_PORT->INDR & OL_GPIO_13_PIN)
#define GPIO_14_DIGITAL_READ() (OL_GPIO_14_PORT->INDR & OL_GPIO_14_PIN)
#define GPIO_15_DIGITAL_READ() (OL_GPIO_15_PORT->INDR & OL_GPIO_15_PIN)
#define GPIO_16_DIGITAL_READ() (OL_GPIO_16_PORT->INDR & OL_GPIO_16_PIN)

// Generic (lookup table function)
void gpio_digital_write(unsigned int pin, unsigned int vin);
uint8_t gpio_digital_read(int pin);

#endif /* USER_OL_LIB_H_ */
